# Spring settings
spring:
    application:
        name: tickr-module

# Kafka settings
kafka:
  enabled: ${KAFKA_ENABLED:true}
  url: ${KAFKA_URL:}
  group-id: ${KAFKA_GROUP_ID:}

# Tracing settings
tracing:
  enabled: ${TRACING_ENABLED:true}
  url: ${TRACING_URL:}

# Management details
management:
  tracing:
    sampling:
      probability: 1.0
  endpoints:
    web:
      exposure:
        include: health,metrics,prometheus
  endpoint:
    prometheus:
      access: READ_ONLY

# Quartz settings
scheduler:
  tasks:
    - name: sendTestHttpRequest
      cron: "0 * * * * ?" # Every minute
      http:
        method: GET
        url: http://example.com
        body: null
    - name: customJob
      cron: "0 * * * * ?" # Every minute
      custom:
        message: test
    - name: kafkaJob
      cron: "0 * * * * ?" # Every minute
      kafka-producer:
        topic: test-topic
        message: test-message
