#Spring settings
spring:
    application:
        name: tickr-module

# Management details
management:
  tracing:
    sampling:
      probability: 1.0
  endpoints:
    web:
      exposure:
        include: health,metrics,prometheus
  endpoint:
    prometheus:
      access: READ_ONLY

# Quartz settings
scheduler:
  tasks:
    - name: sendTestHttpRequest
      cron: "0 * * * * ?" # Every minute
      http:
        method: GET
        url: http://example.com
        body: null
    - name: customJob
      cron: "0 * * * * ?" # Every minute
      custom:
        message: test
