#Spring settings
spring:
    application:
        name: tickr-module

# Quartz settings
scheduler:
  tasks:
    - name: sendTestHttpRequest
      cron: "0 * * * * ?" # Every minute
      http:
        method: GET
        url: http://example.com
        body: null
    - name: customJob
      cron: "0 * * * * ?" # Every minute
      custom:
        message: test
