name: Build and Push Docker image to Nexus

on:
  workflow_dispatch:

env:
  IMAGE_NAME: ${{ secrets.DOCKER_REGISTRY }}/${{ github.event.repository.name }}:${{ github.ref_name }}

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout repository
      - name: 🛎️ Checkout code
        uses: actions/checkout@v4

      # 2️⃣ Set up JDK 21
      - name: ☕ Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      # 3️⃣ Set up Gradle cache
      - name: 🔧 Set up Gradle
        uses: gradle/gradle-build-action@v3

      # 4️⃣ Build JAR with Gradle
      - name: ⚡ Build JAR with Gradle
        run: ./gradlew bootJar

      # 5️⃣ Load APPNAME and VERSION from local.env and set JAR_FILE
      - name: 📄 Load APPNAME, VERSION and set JAR_FILE
        id: load_env
        run: |
          APPNAME=$(grep APPNAME local.env | cut -d'=' -f2)
          VERSION=$(grep VERSION local.env | cut -d'=' -f2)
          echo "APPNAME=$APPNAME" >> $GITHUB_ENV
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "JAR_FILE=build/libs/${APPNAME}-${VERSION}.jar" >> $GITHUB_ENV

      - name: 📄 Find generated JAR
        id: find_jar
        run: |
          # Find the first JAR that contains 'tickr' in its name
          JAR_FILE=$(find . -type f -name "*.jar" | grep "tickr" | head -n1)
          if [ -z "$JAR_FILE" ]; then
            echo "Error: No JAR found!"
            exit 1
          fi
          echo "JAR_FILE=$JAR_FILE" >> $GITHUB_ENV
          echo "Found JAR: $JAR_FILE"
          
      # 6️⃣ Verify JAR exists
      - name: ✅ Check if JAR exists
        run: |
          if [ ! -f "${{ env.JAR_FILE }}" ]; then
            echo "Error: JAR file '${{ env.JAR_FILE }}' does not exist!"
            exit 1
          fi

      # 7️⃣ Set up Docker Buildx
      - name: 🔧 Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # 8️⃣ Login to Docker Registry (Nexus)
      - name: 🔑 Log in to Docker Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.DOCKER_REGISTRY }}
          username: ${{ secrets.NEXUS_USERNAME }}
          password: ${{ secrets.NEXUS_PASSWORD }}

      # 9️⃣ Build and push Docker image
      - name: 🛠️ Build and 🚀 Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ env.IMAGE_NAME }}
          build-args: |
            JAR_FILE=${{ env.JAR_FILE }}
