name: Manual Docker Build and Push

on:
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Set insecure registry
        run: |
          echo "{ \"insecure-registries\": [\"${{ secrets.DOCKER_REGISTRY }}\"] }" | sudo tee /etc/docker/daemon.json
          sudo service docker restart
    
      - name: Checkout code (selected ref)
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          buildkitd-config-inline: |
            [registry."${{ secrets.DOCKER_REGISTRY }}"]
              http = true

      - name: Log in to Docker Registry (Nexus)
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.DOCKER_REGISTRY }}
          username: ${{ secrets.NEXUS_USERNAME }}
          password: ${{ secrets.NEXUS_PASSWORD }}

      - name: Extract tag or branch name
        run: |
          IMAGE_TAG="${GITHUB_REF##*/}"
          REPO_NAME="${GITHUB_REPOSITORY##*/}"
          echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_ENV
          echo "REPO_NAME=$REPO_NAME" >> $GITHUB_ENV

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: ${{ secrets.DOCKER_REGISTRY }}/${{ env.REPO_NAME }}:${{ env.IMAGE_TAG }}
